# Generated by Django 4.2.10 on 2024-02-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_item", models.IntegerField(default=0)),
                (
                    "items",
                    models.ManyToManyField(
                        related_name="products", to="product.product"
                    ),
                ),
            ],
        ),
    ]
